name: sivvai_bookkeeper
description: "A bookkeeping app to record business or personal transactions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  provider: ^6.1.1
  intl: ^0.20.3
  url_launcher: ^6.2.5
  share_plus: ^10.1.4
  file_picker: ^9.0.0
  fl_chart: ^1.2.0
  local_auth: ^3.0.2
  flutter_contacts: ^2.1.0
  shared_preferences: ^2.3.2
  permission_handler: ^13.0.0
  flutter_native_splash: ^2.4.1
  pdf: ^3.10.8
  excel: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8



flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_logo_light.png
  color_dark: "#010108"
  image_dark: assets/app_logo_dark.png

  android_12:
    color: "#FFFFFF"
    image: assets/app_logo_light.png
    color_dark: "#010108"
    image_dark: assets/app_logo_dark.png
flutter:
  uses-material-design: true
  assets:
    - assets/app_splashscreen_dark.png
    - assets/app_splashscreen_light.png
    - assets/app_logo_light.png
    - assets/app_logo_dark.png

